tasks:
  - before: npm install -g yarn
    init: cd theia-electron && yarn add electron-builder --deb
    command: cd theia-electron && yarn && yarn electron-builder --win
image:
  file: .gitpod.Dockerfile
